// packages/markstream-solid/src/components/D2BlockNode.tsx
import type { SolidRenderableNode, SolidRenderContext } from '../node-helpers'
import { createEffect, createSignal, onCleanup } from 'solid-js'
import { getD2 } from '../d2'
import { useSafeI18n } from '../i18n/useSafeI18n'
import { getString } from '../node-helpers'
import { copyTextToClipboard, downloadSvgMarkup } from '../richBlockHelpers'
import { extractRenderedSvg, toSafeSvgMarkup } from '../sanitizeSvg'
import { hideTooltip, showTooltipForAnchor } from '../tooltip/singletonTooltip'

const DARK_THEME_OVERRIDES: Record<string, string> = {
  N1: '#E5E7EB',
  N2: '#CBD5E1',
  N3: '#94A3B8',
  N4: '#64748B',
  N5: '#475569',
  N6: '#334155',
  N7: '#0B1220',
  B1: '#60A5FA',
  B2: '#3B82F6',
  B3: '#2563EB',
  B4: '#1D4ED8',
  B5: '#1E40AF',
  B6: '#111827',
  AA2: '#22D3EE',
  AA4: '#0EA5E9',
  AA5: '#0284C7',
  AB4: '#FBBF24',
  AB5: '#F59E0B',
}

export interface D2BlockNodeProps {
  node: SolidRenderableNode
  context?: SolidRenderContext
  loading?: boolean
  isDark?: boolean
  maxHeight?: string | null
  themeId?: number | null
  darkThemeId?: number | null
  progressiveRender?: boolean
  progressiveIntervalMs?: number
  showHeader?: boolean
  showModeToggle?: boolean
  showCopyButton?: boolean
  showExportButton?: boolean
  showCollapseButton?: boolean
}

function createD2Instance(ctor: any) {
  if (typeof ctor === 'function') {
    // D2 exposes a lower-case factory constructor in some builds.
    // eslint-disable-next-line new-cap
    const instance = new ctor()
    if (typeof instance?.compile === 'function')
      return instance
    if (typeof ctor.compile === 'function')
      return ctor
  }
  if (typeof ctor?.D2 === 'function')
    return new ctor.D2()
  return typeof ctor?.compile === 'function' ? ctor : null
}

export function D2BlockNode(props: D2BlockNodeProps) {
  const [host, setHost] = createSignal<HTMLDivElement>()
  const [error, setError] = createSignal('')
  const [svgMarkup, setSvgMarkup] = createSignal('')
  const [showSource, setShowSource] = createSignal(false)
  const [collapsed, setCollapsed] = createSignal(false)
  const [copied, setCopied] = createSignal(false)
  let copyTimer: ReturnType<typeof setTimeout> | undefined
  let progressiveTimer: ReturnType<typeof setTimeout> | undefined
  let lastProgressiveRenderAt = 0
  const [progressiveTick, setProgressiveTick] = createSignal(0)
  let generation = 0
  let lastRenderKey = ''
  createEffect(() => {
    const target = host()
    const source = getString((props.node as any).code)
    const dark = props.isDark ?? props.context?.isDark ?? false
    const themeId = props.themeId
    const darkThemeId = props.darkThemeId
    const sourceMode = showSource()
    const isCollapsed = collapsed()
    if (!target)
      return
    void progressiveTick()
    if (!source.trim() || sourceMode || isCollapsed) {
      lastRenderKey = ''
      generation += 1
      target.replaceChildren()
      setError('')
      if (!source.trim())
        setSvgMarkup('')
      return
    }
    const renderKey = `${dark ? 'd' : 'l'}:${String(themeId ?? '')}:${String(darkThemeId ?? '')}:${source}`
    if (renderKey === lastRenderKey)
      return
    const isStreaming = props.loading ?? Boolean((props.node as any).loading)
    const interval = Math.max(0, props.progressiveIntervalMs ?? 120)
    if (props.progressiveRender !== false && isStreaming && interval > 0) {
      const elapsed = Date.now() - lastProgressiveRenderAt
      if (elapsed < interval) {
        if (progressiveTimer)
          clearTimeout(progressiveTimer)
        progressiveTimer = setTimeout(() => {
          progressiveTimer = undefined
          setProgressiveTick(value => value + 1)
        }, interval - elapsed)
        return
      }
    }
    if (progressiveTimer) {
      clearTimeout(progressiveTimer)
      progressiveTimer = undefined
    }
    lastRenderKey = renderKey
    const token = ++generation
    lastProgressiveRenderAt = Date.now()
    void (async () => {
      try {
        const ctor = await getD2()
        const instance = createD2Instance(ctor)
        if (token !== generation || !instance?.compile || !instance?.render)
          throw new Error('D2 renderer is not available.')
        const compiled = await instance.compile(source)
        if (token !== generation)
          return
        const diagram = compiled?.diagram ?? compiled
        const options = { ...(compiled?.renderOptions ?? compiled?.options ?? {}) }
        options.themeID = dark && darkThemeId != null ? darkThemeId : themeId ?? options.themeID
        options.darkThemeID = null
        options.darkThemeOverrides = null
        if (dark) {
          options.themeOverrides = {
            ...DARK_THEME_OVERRIDES,
            ...(options.themeOverrides ?? {}),
          }
        }
        const rendered = await instance.render(diagram, options)
        if (token !== generation)
          return
        const svg = toSafeSvgMarkup(extractRenderedSvg(rendered))
        if (!svg)
          throw new Error('D2 rendered empty SVG.')
        const markup = svg.replace('<svg', '<svg class="markstream-d2-root-svg"')
        target.innerHTML = markup
        setSvgMarkup(markup)
        setError('')
      }
      catch (reason) {
        if (token !== generation)
          return
        target.replaceChildren()
        setSvgMarkup('')
        setError(reason instanceof Error ? reason.message : String(reason))
      }
    })()
  })
  onCleanup(() => {
    generation += 1
    if (copyTimer)
      clearTimeout(copyTimer)
    if (progressiveTimer)
      clearTimeout(progressiveTimer)
  })
  const { t } = useSafeI18n()
  const resolvedShowHeader = () => props.showHeader ?? true
  const resolvedShowModeToggle = () => props.showModeToggle ?? true
  const resolvedShowCopyButton = () => props.showCopyButton ?? true
  const resolvedShowExportButton = () => props.showExportButton ?? true
  const resolvedShowCollapseButton = () => props.showCollapseButton ?? true
  const isStreaming = () => props.loading ?? Boolean((props.node as any).loading)
  const showLoading = () => !showSource() && !collapsed() && !svgMarkup() && isStreaming()
  const fallbackVisible = () => !showLoading() && (showSource() || !!error() || !svgMarkup())
  const resolvedIsDark = () => props.isDark ?? props.context?.isDark ?? false
  const showButtonTooltip = (event: MouseEvent | FocusEvent, text: string) => {
    const target = event.currentTarget as HTMLElement | null
    if (!target || (target instanceof HTMLButtonElement && target.disabled))
      return
    showTooltipForAnchor(target, text, 'top', false, undefined, resolvedIsDark())
  }
  const hideBtnTooltip = () => hideTooltip()
  return (
    <div class={`markstream-solid-enhanced-block markstream-solid-enhanced-block--d2${(props.isDark ?? props.context?.isDark) ? ' dark' : ''}${isStreaming() || showLoading() ? ' is-rendering' : ''}`} data-markstream-d2="1" data-markstream-mode={showLoading() ? 'loading' : fallbackVisible() ? 'fallback' : 'preview'}>
      {resolvedShowHeader() && (
        <div class="markstream-solid-enhanced-block__header d2-block-header">
          <span class="d2-label">D2</span>
          <div class="markstream-solid-enhanced-block__actions d2-header-actions">
            {resolvedShowModeToggle() && (
              <div class="d2-mode-toggle">
                <button type="button" class={`d2-mode-btn${!showSource() ? ' is-active' : ''}`} onBlur={hideBtnTooltip} onClick={() => setShowSource(false)} onFocus={event => showButtonTooltip(event, t('common.preview') || 'Preview')} onMouseLeave={hideBtnTooltip} onMouseEnter={event => showButtonTooltip(event, t('common.preview') || 'Preview')}>{t('common.preview')}</button>
                <button type="button" class={`d2-mode-btn${showSource() ? ' is-active' : ''}`} onBlur={hideBtnTooltip} onClick={() => setShowSource(true)} onFocus={event => showButtonTooltip(event, t('common.source') || 'Source')} onMouseLeave={hideBtnTooltip} onMouseEnter={event => showButtonTooltip(event, t('common.source') || 'Source')}>{t('common.source')}</button>
              </div>
            )}
            {resolvedShowCopyButton() && (
              <button
                type="button"
                class="d2-action-btn"
                aria-label={copied() ? t('common.copied') : t('common.copy')}
                onBlur={hideBtnTooltip}
                onClick={() => {
                  const source = getString((props.node as any).code)
                  void copyTextToClipboard(source)
                  props.context?.events?.onCopy?.(source)
                  setCopied(true)
                  if (copyTimer)
                    clearTimeout(copyTimer)
                  copyTimer = setTimeout(() => setCopied(false), 1000)
                }}
                onFocus={event => showButtonTooltip(event, copied() ? (t('common.copied') || 'Copied') : (t('common.copy') || 'Copy'))}
                onMouseLeave={hideBtnTooltip}
                onMouseEnter={event => showButtonTooltip(event, copied() ? (t('common.copied') || 'Copied') : (t('common.copy') || 'Copy'))}
              >
                {copied() ? t('common.copied') : t('common.copy')}
              </button>
            )}
            {resolvedShowExportButton() && (
              <button
                type="button"
                class="d2-action-btn"
                aria-label={t('common.export')}
                disabled={!svgMarkup() || showSource() || collapsed()}
                onBlur={hideBtnTooltip}
                onClick={() => downloadSvgMarkup(svgMarkup(), `d2-diagram-${Date.now()}.svg`)}
                onFocus={event => showButtonTooltip(event, t('common.export') || 'Export')}
                onMouseLeave={hideBtnTooltip}
                onMouseEnter={event => showButtonTooltip(event, t('common.export') || 'Export')}
              >
                {t('common.export')}
              </button>
            )}
            {resolvedShowCollapseButton() && (
              <button
                type="button"
                class="d2-action-btn"
                aria-label={collapsed() ? t('common.expand') : t('common.collapse')}
                aria-pressed={collapsed() ? 'true' : 'false'}
                onBlur={hideBtnTooltip}
                onClick={() => setCollapsed(value => !value)}
                onFocus={event => showButtonTooltip(event, collapsed() ? (t('common.expand') || 'Expand') : (t('common.collapse') || 'Collapse'))}
                onMouseLeave={hideBtnTooltip}
                onMouseEnter={event => showButtonTooltip(event, collapsed() ? (t('common.expand') || 'Expand') : (t('common.collapse') || 'Collapse'))}
              >
                {collapsed() ? t('common.expand') : t('common.collapse')}
              </button>
            )}
          </div>
        </div>
      )}
      <div ref={setHost} class="d2-svg" hidden={fallbackVisible() || collapsed() || showLoading()} style={{ 'max-height': props.maxHeight || undefined, '--ms-d2-render-max-height': props.maxHeight || undefined }} />
      {showLoading() && (
        <div class="d2-loading mermaid-loading" data-markstream-diagram-loading="d2">
          <span class="mermaid-spinner" />
          {t('common.preview')}
        </div>
      )}
      <pre class="d2-source-fallback" hidden={!fallbackVisible() || collapsed()}>
        {getString((props.node as any).code)}
        {error() && !isStreaming() ? `\n${error()}` : ''}
      </pre>
    </div>
  )
}

// packages/markstream-svelte/src/components/D2BlockNode.svelte
<script lang="ts">
  import type { SvelteRenderableNode, SvelteRenderContext } from './shared/node-helpers'
  import { onDestroy, onMount, untrack } from 'svelte'
  import { useSafeI18n } from '../i18n/useSafeI18n'
  import { getD2 } from '../optional/d2'
  import { extractRenderedSvg, toSafeSvgMarkup } from '../sanitizeSvg'
  import { hideTooltip, showTooltipForAnchor } from '../tooltip/singletonTooltip'
  import { createD2RenderSalt } from '../utils/d2RenderSalt'
  import { copyTextToClipboard, downloadSvgMarkup } from './shared/rich-block-helpers'
  import { getString } from './shared/node-helpers'

  const DARK_THEME_OVERRIDES: Record<string, string> = {
    N1: '#E5E7EB',
    N2: '#CBD5E1',
    N3: '#94A3B8',
    N4: '#64748B',
    N5: '#475569',
    N6: '#334155',
    N7: '#0B1220',
    B1: '#60A5FA',
    B2: '#3B82F6',
    B3: '#2563EB',
    B4: '#1D4ED8',
    B5: '#1E40AF',
    B6: '#111827',
    AA2: '#22D3EE',
    AA4: '#0EA5E9',
    AA5: '#0284C7',
    AB4: '#FBBF24',
    AB5: '#F59E0B',
  }

  type Props = {
    node: SvelteRenderableNode
    context?: SvelteRenderContext | undefined
    maxHeight?: string | null | undefined
    loading?: boolean | undefined
    isDark?: boolean | undefined
    themeId?: number | null | undefined
    darkThemeId?: number | null | undefined
    showHeader?: boolean
    showModeToggle?: boolean
    showCopyButton?: boolean
    showExportButton?: boolean
    showCollapseButton?: boolean
  }

  let {
    node,
    context = undefined,
    maxHeight = undefined,
    loading = undefined,
    isDark = undefined,
    themeId = undefined,
    darkThemeId = undefined,
    showHeader = true,
    showModeToggle = true,
    showCopyButton = true,
    showExportButton = true,
    showCollapseButton = true
  }: Props = $props()

  const { t } = useSafeI18n()

  let mounted = $state(false)
  let renderToken = $state(0)
  let lastSignature = $state('')
  let activeRenderSignature = $state('')
  let svgMarkup = $state('')
  let renderError = $state('')
  let rendering = $state(false)
  let rerenderQueued = $state(false)
  let rerenderForce = $state(false)
  let copied = $state(false)
  let collapsed = $state(false)
  let showSource = $state(false)
  let copyTimer: ReturnType<typeof setTimeout> | null = null

  let source = $derived(getString((node as any)?.code))
  let resolvedLoading = $derived(loading ?? (node as any)?.loading === true)
  let resolvedIsDark = $derived(isDark ?? context?.isDark ?? false)
  let shouldRender = $derived(!(resolvedLoading && !source.trim()))
  let showSourceFallback = $derived(showSource || !svgMarkup)
  // Expose the same cap to the stylesheet (via --ms-d2-render-max-height)
  // so the root svg can scale down proportionally to the container's
  // max-height; see the .d2-svg svg rule in index.css.
  let renderStyle = $derived(maxHeight
    ? `max-height: ${maxHeight}; --ms-d2-render-max-height: ${maxHeight}`
    : '')

  onMount(() => {
    mounted = true
    void renderD2(true)
  })

  $effect(() => {
    if (mounted) {
      const _sig = getRenderSignature()
      const _collapsed = collapsed
      const _showSource = showSource
      untrack(() => {
        void renderD2()
      })
    }
  })

  onDestroy(() => {
    mounted = false
    renderToken += 1
    if (copyTimer)
      clearTimeout(copyTimer)
  })

  async function renderD2(force = false) {
    if (!mounted || collapsed || showSource || !source.trim())
      return
    const signature = getRenderSignature()
    if (rendering) {
      if (signature !== activeRenderSignature || force) {
        rerenderQueued = true
        rerenderForce = rerenderForce || force
      }
      return
    }
    if (!force && signature === lastSignature && (svgMarkup || renderError))
      return

    const token = ++renderToken
    activeRenderSignature = signature
    lastSignature = signature
    rendering = true
    renderError = ''
    try {
      const D2Ctor = await getD2()
      if (!mounted || token !== renderToken)
        return
      const instance = createD2Instance(D2Ctor)
      if (!instance || typeof instance.compile !== 'function' || typeof instance.render !== 'function')
        throw new Error('D2 renderer is not available.')

      const compileResult = await instance.compile(source)
      const diagram = compileResult?.diagram ?? compileResult
      const baseRenderOptions = compileResult?.renderOptions ?? compileResult?.options ?? {}
      const renderOptions: Record<string, any> = { ...baseRenderOptions }
      renderOptions.themeID = resolvedIsDark && darkThemeId != null
        ? darkThemeId
        : themeId ?? baseRenderOptions.themeID
      renderOptions.darkThemeID = null
      renderOptions.darkThemeOverrides = null
      if (resolvedIsDark) {
        renderOptions.themeOverrides = {
          ...DARK_THEME_OVERRIDES,
          ...(baseRenderOptions.themeOverrides || {}),
        }
      }

      renderOptions.salt = renderOptions.salt ?? createD2RenderSalt()
      const rendered = await instance.render(diagram, renderOptions)
      if (!mounted || token !== renderToken)
        return
      const safeSvg = toSafeSvgMarkup(extractRenderedSvg(rendered))
      if (!safeSvg)
        throw new Error('D2 rendered empty SVG.')
      svgMarkup = safeSvg.replace('<svg', '<svg class="markstream-d2-root-svg"')
    }
    catch (error) {
      if (token === renderToken) {
        svgMarkup = ''
        renderError = error instanceof Error ? error.message : String(error)
      }
    }
    finally {
      if (token === renderToken) {
        rendering = false
        activeRenderSignature = ''
        if (rerenderQueued) {
          const forceNext = rerenderForce
          rerenderQueued = false
          rerenderForce = false
          void renderD2(forceNext)
        }
      }
    }
  }

  function getRenderSignature() {
    return `${source}\n${resolvedIsDark}\n${themeId}\n${darkThemeId}`
  }

  function createD2Instance(D2Ctor: any) {
    if (typeof D2Ctor === 'function') {
      const instance = new D2Ctor()
      if (instance && typeof instance.compile === 'function')
        return instance
      if (typeof D2Ctor.compile === 'function')
        return D2Ctor
    }
    if (D2Ctor?.D2 && typeof D2Ctor.D2 === 'function')
      return new D2Ctor.D2()
    if (typeof D2Ctor?.compile === 'function')
      return D2Ctor
    return null
  }

  async function copy() {
    await copyTextToClipboard(source)
    context?.events?.onCopy?.(source)
    copied = true
    if (copyTimer)
      clearTimeout(copyTimer)
    copyTimer = setTimeout(() => {
      copied = false
    }, 1000)
  }

  function exportSvg() {
    if (svgMarkup)
      downloadSvgMarkup(svgMarkup, `d2-diagram-${Date.now()}.svg`)
  }

  function switchMode(mode: 'preview' | 'source') {
    showSource = mode === 'source'
    if (!showSource)
      void renderD2(true)
  }

  function showButtonTooltip(event: MouseEvent | FocusEvent, text: string) {
    const target = event.currentTarget as HTMLElement | null
    if (!target || (target instanceof HTMLButtonElement && target.disabled))
      return
    showTooltipForAnchor(target, text, 'top', false, undefined, resolvedIsDark)
  }

  function showCopyTooltip(event: MouseEvent | FocusEvent) {
    showButtonTooltip(event, copied ? (t('common.copied') || 'Copied') : (t('common.copy') || 'Copy'))
  }
</script>

{#if shouldRender}
  <div
    class:dark={resolvedIsDark}
    class:is-rendering={rendering || resolvedLoading}
    class="markstream-svelte-enhanced-block markstream-svelte-enhanced-block--d2"
    data-markstream-d2="1"
    data-markstream-mode={showSourceFallback ? 'fallback' : 'preview'}
  >
    {#if showHeader}
      <div class="markstream-svelte-enhanced-block__header d2-block-header">
        <div class="d2-header-title">
          <span class="d2-label">D2</span>
        </div>
        <div class="markstream-svelte-enhanced-block__actions d2-header-actions">
          {#if showModeToggle}
            <div class="d2-mode-toggle">
              <button type="button" class:is-active={!showSource} class="markstream-svelte-enhanced-block__action mode-btn d2-mode-btn" onblur={() => hideTooltip()} onclick={() => switchMode('preview')} onfocus={(event) => showButtonTooltip(event, t('common.preview') || 'Preview')} onmouseleave={() => hideTooltip()} onmouseenter={(event) => showButtonTooltip(event, t('common.preview') || 'Preview')}>{t('common.preview')}</button>
              <button type="button" class:is-active={showSource} class="markstream-svelte-enhanced-block__action mode-btn d2-mode-btn" onblur={() => hideTooltip()} onclick={() => switchMode('source')} onfocus={(event) => showButtonTooltip(event, t('common.source') || 'Source')} onmouseleave={() => hideTooltip()} onmouseenter={(event) => showButtonTooltip(event, t('common.source') || 'Source')}>{t('common.source')}</button>
            </div>
          {/if}
          {#if showCopyButton}
            <button type="button" class="markstream-svelte-enhanced-block__action markstream-svelte-enhanced-block__action--icon d2-action-btn" aria-label={copied ? (t('common.copied') || 'Copied') : (t('common.copy') || 'Copy')} onblur={() => hideTooltip()} onclick={copy} onfocus={showCopyTooltip} onmouseleave={() => hideTooltip()} onmouseenter={showCopyTooltip}>
              {#if copied}
                <svg aria-hidden="true" role="img" viewBox="0 0 24 24"><path fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M20 6L9 17l-5-5"/></svg>
              {:else}
                <svg aria-hidden="true" role="img" viewBox="0 0 24 24"><g fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"><rect width="14" height="14" x="8" y="8" rx="2" ry="2"/><path d="M4 16c-1.1 0-2-.9-2-2V4c0-1.1.9-2 2-2h10c1.1 0 2 .9 2 2"/></g></svg>
              {/if}
            </button>
          {/if}
          {#if showExportButton && svgMarkup}
            <button type="button" class="markstream-svelte-enhanced-block__action markstream-svelte-enhanced-block__action--icon d2-action-btn" aria-label={t('common.export') || 'Export'} onblur={() => hideTooltip()} onclick={exportSvg} onfocus={(event) => showButtonTooltip(event, t('common.export') || 'Export')} onmouseleave={() => hideTooltip()} onmouseenter={(event) => showButtonTooltip(event, t('common.export') || 'Export')}>
              <svg aria-hidden="true" role="img" viewBox="0 0 24 24"><path fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 3v12m0-12l-4 4m4-4l4 4M4 14v4a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2v-4"/></svg>
            </button>
          {/if}
          {#if showCollapseButton}
            <button type="button" class="markstream-svelte-enhanced-block__action markstream-svelte-enhanced-block__action--icon d2-action-btn" aria-label={collapsed ? (t('common.expand') || 'Expand') : (t('common.collapse') || 'Collapse')} aria-pressed={collapsed} onblur={() => hideTooltip()} onclick={() => (collapsed = !collapsed)} onfocus={(event) => showButtonTooltip(event, collapsed ? (t('common.expand') || 'Expand') : (t('common.collapse') || 'Collapse'))} onmouseleave={() => hideTooltip()} onmouseenter={(event) => showButtonTooltip(event, collapsed ? (t('common.expand') || 'Expand') : (t('common.collapse') || 'Collapse'))}>
              <svg aria-hidden="true" role="img" style:transform={collapsed ? 'rotate(0deg)' : 'rotate(90deg)'} viewBox="0 0 24 24"><path fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m9 18l6-6l-6-6"/></svg>
            </button>
          {/if}
        </div>
      </div>
    {/if}

    {#if !collapsed}
      <div class="markstream-svelte-enhanced-block__body d2-block-body">
        {#if showSourceFallback}
          <div class="d2-source">
            <pre class="d2-code"><code>{source}</code></pre>
            {#if renderError}
              <p class="d2-error">{renderError}</p>
            {/if}
          </div>
        {:else}
          <div class="d2-render" style={renderStyle}>
            <div class="d2-svg">{@html svgMarkup}</div>
            {#if renderError}
              <p class="d2-error">{renderError}</p>
            {/if}
          </div>
        {/if}
      </div>
    {/if}
  </div>
{/if}
