// packages/markstream-angular/src/components/FootnoteReferenceNode/FootnoteReferenceNode.component.ts
import type { AngularRenderableNode } from '../shared/node-helpers'
import { ChangeDetectionStrategy, Component, Input } from '@angular/core'
import { findFootnoteElement } from '../../utils/footnoteTarget'
import { getString } from '../shared/node-helpers'

@Component({
  selector: 'markstream-angular-footnote-reference-node',
  standalone: true,
  template: `
    <sup [attr.id]="referenceId" class="markstream-nested-footnote-ref">
      <a [attr.href]="href" (click)="handleClick($event)">[{{ id }}]</a>
    </sup>
  `,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class FootnoteReferenceNodeComponent {
  @Input({ required: true }) node!: AngularRenderableNode

  get id() {
    return getString((this.node as any)?.id)
  }

  get href() {
    return `#fnref--${this.id}`
  }

  get referenceId() {
    return `fnref-${this.id}`
  }

  handleClick(event: MouseEvent) {
    event.preventDefault()
    if (typeof document === 'undefined')
      return
    const target = findFootnoteElement(event.currentTarget, `fnref--${this.id}`)
    target?.scrollIntoView({ behavior: 'smooth' })
  }
}

// packages/markstream-svelte/src/components/FootnoteReferenceNode.svelte
<script lang="ts">
  import type { SvelteRenderableNode } from './shared/node-helpers'
  import { getString } from './shared/node-helpers'
  import { findFootnoteElement } from '../utils/footnoteTarget'

  interface Props {
    node: SvelteRenderableNode
  }

  let { node }: Props = $props()

  let id = $derived(getString((node as any)?.id))
  let href = $derived(id ? `#fnref--${id}` : undefined)
  let linkAttrs = $derived(href ? { href } : {})

  function scrollToFootnote(event: MouseEvent) {
    event.preventDefault()
    if (typeof document === 'undefined' || !id)
      return
    const target = findFootnoteElement(event.currentTarget, `fnref--${id}`)
    target?.scrollIntoView({ behavior: 'smooth', block: 'start' })
  }
</script>

<!-- svelte-ignore a11y_click_events_have_key_events -->
<!-- svelte-ignore a11y_no_noninteractive_element_interactions -->
<sup id={id ? `fnref-${id}` : undefined} class="footnote-reference" onclick={scrollToFootnote}>
  <span {...linkAttrs} title={id ? `查看脚注 ${id}` : undefined} class="footnote-link cursor-pointer">
    [{id}]
  </span>
</sup>
