// packages/markstream-angular/src/components/InlineCodeNode/InlineCodeNode.component.ts
import type { OnChanges } from '@angular/core'
import type { AngularRenderableNode, AngularRenderContext } from '../shared/node-helpers'
import { CommonModule } from '@angular/common'
import { ChangeDetectionStrategy, Component, Input } from '@angular/core'
import { resolveStreamingTextState } from 'markstream-core'
import { getString } from '../shared/node-helpers'

@Component({
  selector: 'markstream-angular-inline-code-node',
  standalone: true,
  imports: [CommonModule],
  template: `
    <code>
      <span *ngIf="settledCode">{{ settledCode }}</span>
      <span
        *ngIf="streamedDelta"
        [class]="'markstream-angular-text__stream-delta ' + streamedDeltaClass"
        (animationend)="settleStreamedDelta()"
      >{{ streamedDelta }}</span>
    </code>
  `,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class InlineCodeNodeComponent implements OnChanges {
  @Input({ required: true }) node!: AngularRenderableNode
  @Input() context?: AngularRenderContext
  @Input() indexKey?: string
  @Input() typewriter?: boolean
  @Input() fade?: boolean

  settledCode = ''
  streamedDelta = ''
  private streamFadeVersion = 0

  ngOnChanges() {
    const nextCode = getString((this.node as any)?.code)
    const streamStateKey = getString(this.indexKey).trim()
    const textStreamState = this.context?.textStreamState
    const rendered = `${this.settledCode}${this.streamedDelta}`
    const previousPersisted = streamStateKey
      ? textStreamState?.get(streamStateKey)
      : undefined
    const previousCode = previousPersisted ?? rendered

    const nextState = resolveStreamingTextState({
      nextContent: nextCode,
      previousContent: previousCode,
      typewriterEnabled: this.fadeEnabled,
    })

    this.settledCode = nextState.settledContent
    this.streamedDelta = nextState.streamedDelta
    if (nextState.appended)
      this.streamFadeVersion += 1
    if (streamStateKey)
      textStreamState?.set(streamStateKey, nextCode)
  }

  get streamedDeltaClass() {
    return this.streamFadeVersion % 2 === 0
      ? 'markstream-angular-text__stream-delta--a'
      : 'markstream-angular-text__stream-delta--b'
  }

  get fadeEnabled() {
    if (typeof this.fade === 'boolean')
      return this.fade
    if (typeof this.context?.fade === 'boolean')
      return this.context.fade
    return true
  }

  get typewriterEnabled() {
    if (typeof this.typewriter === 'boolean')
      return this.typewriter
    if (typeof this.context?.typewriter === 'boolean')
      return this.context.typewriter
    return false
  }

  settleStreamedDelta() {
    if (!this.streamedDelta)
      return
    this.settledCode = `${this.settledCode}${this.streamedDelta}`
    this.streamedDelta = ''
  }
}

// packages/markstream-svelte/src/components/InlineCodeNode.svelte
<script lang="ts">
  import type { SvelteRenderableNode, SvelteRenderContext } from './shared/node-helpers'
  import { resolveStreamingTextState } from 'markstream-core'
  import { getString } from './shared/node-helpers'

  interface Props {
    node: SvelteRenderableNode
    context?: SvelteRenderContext
    indexKey?: string | number
  }

  let {
    node,
    context = undefined,
    indexKey = undefined,
  }: Props = $props()

  let previousKey = ''
  let previousCode = ''
  let deltaClass = 'markstream-svelte-text__stream-delta--a'

  const code = $derived(getString((node as any)?.code ?? (node as any)?.content ?? (node as any)?.raw))
  const streamKey = $derived(
    `${String(context?.customId ?? 'global')}:${String(context?.streamRenderVersion ?? 0)}:${String(indexKey ?? 'inline-code')}`,
  )
  const fadeEnabled = $derived(context?.fade !== false)

  const streamInfo = $derived.by(() => {
    const state = context?.textStreamState
    const previous = streamKey === previousKey
      ? previousCode
      : (state?.get(streamKey) ?? '')

    const result = resolveStreamingTextState({
      nextContent: code,
      previousContent: previous,
      typewriterEnabled: fadeEnabled,
    })

    if (result.appended) {
      deltaClass = deltaClass.endsWith('--a')
        ? 'markstream-svelte-text__stream-delta--b'
        : 'markstream-svelte-text__stream-delta--a'
    }

    previousKey = streamKey
    previousCode = code
    state?.set(streamKey, code)

    return {
      stableCode: result.settledContent,
      deltaCode: result.streamedDelta,
      deltaClass,
    }
  })
</script>

<code class="inline-code-node">
  {streamInfo.stableCode}
  {#if streamInfo.deltaCode}
    <span class="markstream-svelte-text__stream-delta text-node-stream-delta {streamInfo.deltaClass}">
      {streamInfo.deltaCode}
    </span>
  {/if}
</code>
