// src/components/FootnoteReferenceNode/FootnoteReferenceNode.vue
<script setup lang="ts">
import { findFootnoteElement } from '../../utils/footnoteTarget'

// 定义脚注引用节点
interface FootnoteReferenceNode {
  type: 'footnote_reference'
  id: string
  raw: string
}

// 接收props
const props = defineProps<{
  node: FootnoteReferenceNode
}>()
const href = `#fnref--${props.node.id}`
function handleScroll(event: MouseEvent) {
  if (typeof document === 'undefined') {
    // SSR: nothing to do
    return
  }
  const element = findFootnoteElement(event.currentTarget, `fnref--${props.node.id}`)
  if (element) {
    element.scrollIntoView({ behavior: 'smooth' })
  }
  else {
    console.warn(`Element with href: ${href} not found`)
  }
}
</script>

<template>
  <sup :id="`fnref-${node.id}`" class="footnote-reference" @click="handleScroll">
    <span
      :href="href"
      :title="`查看脚注 ${node.id}`"
      class="footnote-link cursor-pointer"
    >[{{ node.id }}]</span>
  </sup>
</template>

<style scoped>
.footnote-reference {
  font-size: 0.75em;
  line-height: 0;
}

.footnote-link {
  color: var(--link-color);
  text-decoration: none;
}

.footnote-link:hover {
  text-decoration: underline;
}
</style>

// packages/markstream-react/src/components/FootnoteReferenceNode/FootnoteReferenceNode.tsx
import type { NodeComponentProps } from '../../types/node-component'
import React, { useCallback, useMemo } from 'react'
import { findFootnoteElement } from '../../utils/footnoteTarget'

export function FootnoteReferenceNode(props: NodeComponentProps<{ type: 'footnote_reference', id: string }>) {
  const { node } = props
  const href = useMemo(() => `#fnref--${node.id}`, [node.id])
  const linkAttrs = useMemo(() => ({ href }) as React.HTMLAttributes<HTMLSpanElement> & { href: string }, [href])
  const handleScroll = useCallback((event: React.MouseEvent) => {
    event.preventDefault()
    if (typeof document === 'undefined')
      return
    const target = findFootnoteElement(event.currentTarget, `fnref--${node.id}`)
    if (target)
      target.scrollIntoView({ behavior: 'smooth' })
  }, [node.id])

  return (
    <sup id={`fnref-${node.id}`} className="footnote-reference" onClick={handleScroll}>
      <span {...linkAttrs} title={`查看脚注 ${node.id}`} className="footnote-link cursor-pointer">
        [
        {node.id}
        ]
      </span>
    </sup>
  )
}

export default FootnoteReferenceNode
