// packages/markstream-vue2/src/components/TextNode/TextNode.vue
<script setup lang="ts">
import { useKatexReady } from '../../composables/useKatexReady'

defineProps<{
  node: {
    type: 'text'
    content: string
    raw: string
    center?: boolean
  }
}>()
defineEmits(['copy'])
const katexReady = useKatexReady()
</script>

<template>
  <span
    :class="[katexReady && node.center ? 'text-node-center' : '']"
    class="whitespace-pre-wrap break-words text-node"
  >
    {{ node.content }}
  </span>
</template>

<style scoped>
.text-node {
  display: inline;
  font-weight: inherit;
  vertical-align: baseline;
}
.text-node-center {
  display: inline-flex;
  justify-content: center;
  width: 100%;
}
</style>

// packages/markstream-react/src/components/TextNode/TextNode.tsx
import type { NodeComponentProps } from '../../types/node-component'
import clsx from 'clsx'
import React from 'react'

export function TextNode(props: NodeComponentProps<{ type: 'text', content: string, center?: boolean }>) {
  const { node, children } = props
  return (
    <span
      className={clsx(
        'text-node whitespace-pre-wrap break-words',
        node.center && 'text-node-center',
      )}
    >
      {children ?? node.content}
    </span>
  )
}

export default TextNode
