// packages/markstream-solid/src/composables/useSmoothMarkdownStream.ts
import type { SmoothMarkdownStreamOptions } from 'markstream-core'
import { createSmoothMarkdownStream } from 'markstream-core'
import { createSignal, onCleanup } from 'solid-js'

export type { SmoothMarkdownStreamOptions }

export interface SmoothMarkdownStreamControllerSolid {
  source: () => string
  visible: () => string
  done: () => boolean
  caughtUp: () => boolean
  final: () => boolean
  pendingChars: () => number
  enqueue: (chunk: string) => void
  finish: (options?: { flush?: boolean }) => void
  flush: () => void
  reset: (initialMarkdown?: string) => void
  pause: () => void
  resume: () => void
}

export function useSmoothMarkdownStream(options: SmoothMarkdownStreamOptions = {}): SmoothMarkdownStreamControllerSolid {
  const controller = createSmoothMarkdownStream(options)
  const [snapshot, setSnapshot] = createSignal(controller.getSnapshot())
  const unsubscribe = controller.subscribe(() => setSnapshot(controller.getSnapshot()))
  onCleanup(() => {
    unsubscribe()
    controller.destroy()
  })
  return {
    source: () => snapshot().source,
    visible: () => snapshot().visible,
    done: () => snapshot().done,
    caughtUp: () => snapshot().caughtUp,
    final: () => snapshot().final,
    pendingChars: () => snapshot().pendingChars,
    enqueue: chunk => controller.enqueue(chunk),
    finish: options => controller.finish(options),
    flush: () => controller.flush(),
    reset: initialMarkdown => controller.reset(initialMarkdown),
    pause: () => controller.pause(),
    resume: () => controller.resume(),
  }
}

// packages/markstream-react/src/hooks/useSmoothMarkdownStream.ts
import type {
  SmoothMarkdownStreamOptions,
  SmoothMarkdownStreamSnapshot,
} from 'markstream-core'
import { createSmoothMarkdownStream } from 'markstream-core'
import { useEffect, useMemo, useRef, useState } from 'react'

export type { SmoothMarkdownStreamOptions, SmoothMarkdownStreamSnapshot }

export function useSmoothMarkdownStream(options: SmoothMarkdownStreamOptions = {}) {
  const controllerRef = useRef<ReturnType<typeof createSmoothMarkdownStream> | null>(null)

  if (!controllerRef.current)
    controllerRef.current = createSmoothMarkdownStream(options)

  const controller = controllerRef.current

  const [snapshot, setSnapshot] = useState<SmoothMarkdownStreamSnapshot>(() => controller.getSnapshot())

  useEffect(() => {
    const unsubscribe = controller.subscribe(() => {
      setSnapshot(controller.getSnapshot())
    })

    controller.resume()
    setSnapshot(controller.getSnapshot())

    return () => {
      unsubscribe()
      // Keep controller state across React StrictMode effect replay.
      // pause() stops the loop/subscription without clearing source/visible.
      // On real unmount, the component releases this controller instance.
      controller.pause()
    }
  }, [controller])

  return useMemo(() => ({
    ...snapshot,
    enqueue: controller.enqueue,
    finish: controller.finish,
    flush: controller.flush,
    reset: controller.reset,
    pause: controller.pause,
    resume: controller.resume,
    getSnapshot: controller.getSnapshot,
  }), [controller, snapshot])
}
