// packages/markstream-svelte/src/components/MermaidBlockNode.svelte
<script lang="ts">
  import type { SvelteRenderableNode, SvelteRenderContext } from './shared/node-helpers'
  import { createPanGesture } from 'markstream-core'
  import { onMount, tick, untrack } from 'svelte'
  import { toSafeMermaidSvgMarkup } from 'stream-markdown-parser'
  import { useSafeI18n } from '../i18n/useSafeI18n'
  import { getMermaid } from '../optional/mermaid'
  import { hideTooltip, showTooltipForAnchor, type TooltipPlacement } from '../tooltip/singletonTooltip'
  import { getLanguageIcon } from '../utils/languageIcon'
  import { createMermaidRenderId } from '../utils/mermaidRenderId'
  import { canParseOffthread, findPrefixOffthread } from '../workers/mermaidWorkerClient'
  import { clampPreviewHeight, estimateMermaidPreviewHeight, getMermaidDiagramKind, MERMAID_PREVIEW_MIN_HEIGHT, parsePositiveNumber, resolveDiagramMinPreviewHeight } from './shared/diagram-height'
  import { copyTextToClipboard, downloadSvgMarkup } from './shared/rich-block-helpers'
  import { getString } from './shared/node-helpers'

  type MermaidTheme = 'light' | 'dark'

  type Props = {
    node: SvelteRenderableNode
    context?: SvelteRenderContext
    maxHeight?: string | null
    estimatedPreviewHeightPx?: number
    loading?: boolean
    isDark?: boolean
    workerTimeoutMs?: number
    parseTimeoutMs?: number
    renderTimeoutMs?: number
    fullRenderTimeoutMs?: number
    renderDebounceMs?: number
    showHeader?: boolean
    showModeToggle?: boolean
    showCopyButton?: boolean
    showExportButton?: boolean
    showFullscreenButton?: boolean
    showCollapseButton?: boolean
    showZoomControls?: boolean
    isStrict?: boolean
    enableMermaidInteractions?: boolean
  }

  let {
    node,
    context = undefined,
    maxHeight = '500px',
    estimatedPreviewHeightPx = undefined,
    loading = undefined,
    isDark = undefined,
    workerTimeoutMs = 1400,
    parseTimeoutMs = 1800,
    renderTimeoutMs = 2500,
    fullRenderTimeoutMs = 4000,
    renderDebounceMs = 300,
    showHeader = true,
    showModeToggle = true,
    showCopyButton = true,
    showExportButton = true,
    showFullscreenButton = true,
    showCollapseButton = true,
    showZoomControls = true,
    isStrict = true,
    enableMermaidInteractions = false,
  }: Props = $props()

  const { t } = useSafeI18n()
  const mermaidIcon = getLanguageIcon('mermaid')

  let mounted = $state(false)
  let renderToken = $state(0)
  let lastRenderSignature = $state('')
  let lastProgressiveMissSignature = $state('')
  let lastRenderedCode = $state('')
  let svgMarkup = $state('')
  let svgCache: Partial<Record<MermaidTheme, string>> = $state({})
  let renderError = $state('')
  let rendering = $state(false)
  let hasRenderedOnce = $state(false)
  let copied = $state(false)
  let collapsed = $state(false)
  let showSource = $state(false)
  let modalOpen = $state(false)
  let zoom = $state(1)
  let translateX = $state(0)
  let translateY = $state(0)
  let isDragging = $state(false)
  let blockHost: HTMLElement | null = $state(null)
  let previewHost: HTMLElement | null = $state(null)
  let modalHost: HTMLElement | null = $state(null)
  let renderTimer: ReturnType<typeof setTimeout> | null = $state(null)
  let copyTimer: ReturnType<typeof setTimeout> | null = $state(null)
  let lastMermaidBindFunctions: ((element: Element) => unknown) | null = null

  let source = $derived(normalizeMermaidSource(getString((node as any)?.code)))
  let nodeLoading = $derived(typeof (node as any)?.loading === 'boolean' ? Boolean((node as any)?.loading) : true)
  let resolvedLoading = $derived(loading ?? nodeLoading)
  let resolvedIsDark = $derived(isDark ?? context?.isDark ?? false)
  let theme = $derived((resolvedIsDark ? 'dark' : 'light') as MermaidTheme)
  let final = $derived(context?.final ?? resolvedLoading === false)
  let progressivePreview = $derived(resolvedLoading !== false || final === false)
  let maxPreviewHeight = $derived(maxHeight === 'none' ? null : parsePositiveNumber(maxHeight))
  let previewHeight = $derived(clampPreviewHeight(
    parsePositiveNumber(estimatedPreviewHeightPx) ?? estimateMermaidPreviewHeight(source),
    resolveDiagramMinPreviewHeight(blockHost, MERMAID_PREVIEW_MIN_HEIGHT),
    maxPreviewHeight ?? undefined,
  ))
  let previewStyle = $derived([
    `min-height: ${previewHeight}px`,
    maxHeight && maxHeight !== 'none' ? `max-height: ${maxHeight}` : '',
    `transform: translate(${translateX}px, ${translateY}px) scale(${zoom})`,
    `cursor: ${isDragging ? 'grabbing' : 'grab'}`,
  ].filter(Boolean).join('; '))
  let shouldRender = $derived(!(resolvedLoading && !source.trim()))
  let canUsePreview = $derived(Boolean(svgMarkup && !showSource))

  // The diagram is scaled to fit the preview box, so at fit zoom nothing is
  // off-screen and panning only shifts it inside the box. Touch therefore keeps
  // scrolling the page at that zoom (a chat is mostly scrolling) and only claims
  // the gesture once the diagram is zoomed in and actually overflows the box.
  // The fullscreen modal always claims it.
  let panSurfaceClaimsTouch = $derived(modalOpen || zoom > 1)

  onMount(() => {
    mounted = true
    scheduleRender(true)

    return () => {
      mounted = false
      renderToken += 1
      clearRenderTimer()
      // A drag in progress must not keep its window listeners after unmount.
      panGesture.stop()
      if (copyTimer)
        clearTimeout(copyTimer)
    }
  })

  $effect(() => {
    if (mounted) {
      getRenderSignature()
      showSource
      collapsed
      untrack(() => scheduleRender())
    }
  })

  $effect(() => {
    if (mounted && modalOpen && svgMarkup && modalHost && enableMermaidInteractions)
      untrack(() => void tick().then(() => bindCurrentMermaidInteractions(modalHost)))
  })

  function clearRenderTimer() {
    if (!renderTimer)
      return
    clearTimeout(renderTimer)
    renderTimer = null
  }

  function scheduleRender(force = false) {
    if (!mounted || showSource || collapsed)
      return
    const signature = getRenderSignature()
    if (signature === lastRenderSignature && rendering)
      return
    if (!force && signature === lastRenderSignature && (svgMarkup || renderError || lastProgressiveMissSignature === signature))
      return
    if (force)
      clearRenderTimer()
    if (renderTimer)
      return
    const delay = force || !progressivePreview ? 0 : Math.max(0, renderDebounceMs)
    renderTimer = setTimeout(() => {
      renderTimer = null
      void renderMermaid(force)
    }, delay)
  }

  function normalizeMermaidSource(value: string) {
    return value
      .replace(/\]::([^:])/g, ']:::$1')
      .replace(/:::subgraphNode$/gm, '::subgraphNode')
  }

  function applyMermaidThemeTo(value: string, nextTheme: MermaidTheme) {
    const trimmed = value.trimStart()
    if (trimmed.startsWith('%%{'))
      return value
    const themeValue = nextTheme === 'dark' ? 'dark' : 'default'
    return `%%{init: {"theme": "${themeValue}"}}%%\n${value}`
  }

  async function renderMermaid(force = false) {
    if (!mounted || showSource || collapsed)
      return

    if (!source.trim()) {
      svgMarkup = ''
      renderError = ''
      lastRenderedCode = ''
      lastProgressiveMissSignature = ''
      hasRenderedOnce = false
      svgCache = {}
      return
    }

    const normalized = normalizeRenderedCode(source)
    const signature = getRenderSignature()
    if (signature === lastRenderSignature && rendering)
      return
    if (!force && signature === lastRenderSignature && (svgMarkup || renderError || lastProgressiveMissSignature === signature))
      return

    const token = ++renderToken
    lastRenderSignature = signature
    rendering = true
    if (!progressivePreview)
      renderError = ''

    try {
      const mermaid = await getMermaid({
        startOnLoad: false,
        securityLevel: isStrict ? 'strict' : 'loose',
        suppressErrorRendering: true,
        ...(isStrict ? { flowchart: { htmlLabels: false } } : {}),
      })
      if (!mounted || token !== renderToken)
        return
      if (!mermaid)
        throw new Error('Mermaid is not available.')

      let renderSource = source
      let fullRender = true

      if (progressivePreview) {
        if (hasRenderedOnce && normalized === lastRenderedCode && svgMarkup) {
          renderError = ''
          return
        }
        const parsed = await canParseOrPrefix(source, theme, mermaid)
        if (!mounted || token !== renderToken)
          return
        if (parsed.fullOk) {
          renderSource = source
        }
        else if (parsed.prefixOk && parsed.prefix && !hasRenderedOnce) {
          renderSource = parsed.prefix
          fullRender = false
        }
        else {
          renderError = ''
          lastProgressiveMissSignature = signature
          const cached = svgCache[theme]
          if (cached)
            svgMarkup = cached
          return
        }
      }
      else {
        await canParseMermaid(source, theme, mermaid)
      }

      const rendered = await withTimeout(
        () => Promise.resolve(mermaid.render(createMermaidRenderId(), applyMermaidThemeTo(renderSource, theme))),
        fullRender ? fullRenderTimeoutMs : renderTimeoutMs,
      )
      if (!mounted || token !== renderToken)
        return

      const rawSvg = typeof rendered === 'string' ? rendered : rendered?.svg
      const safeSvg = toSafeMermaidSvgMarkup(rawSvg)
      if (!safeSvg)
        throw new Error('Mermaid rendered empty SVG.')
      svgMarkup = safeSvg
      lastMermaidBindFunctions = typeof rendered === 'string' ? null : rendered?.bindFunctions ?? null
      renderError = ''
      lastProgressiveMissSignature = ''
      if (fullRender) {
        hasRenderedOnce = true
        lastRenderedCode = normalized
        svgCache[theme] = safeSvg
      }
      if (enableMermaidInteractions && typeof rendered !== 'string') {
        await tick()
        if (mounted && token === renderToken) {
          bindCurrentMermaidInteractions(previewHost)
          if (modalOpen)
            bindCurrentMermaidInteractions(modalHost)
        }
      }
    }
    catch (error) {
      if (token === renderToken) {
        if (progressivePreview) {
          renderError = ''
          lastProgressiveMissSignature = signature
        }
        else {
          svgMarkup = ''
          renderError = error instanceof Error ? error.message : String(error)
        }
      }
    }
    finally {
      if (token === renderToken)
        rendering = false
    }
  }

  async function canParseMermaid(value: string, nextTheme: MermaidTheme, mermaid: any) {
    try {
      if (await canParseOffthread(value, nextTheme, workerTimeoutMs))
        return true
    }
    catch {}

    const themedSource = applyMermaidThemeTo(value, nextTheme)
    if (typeof mermaid?.parse === 'function') {
      await withTimeout(() => Promise.resolve(mermaid.parse(themedSource)), parseTimeoutMs)
      return true
    }
    await withTimeout(() => Promise.resolve(mermaid.render(createMermaidRenderId('markstream-svelte-mermaid-parse'), themedSource)), parseTimeoutMs)
    return true
  }

  async function canParseOrPrefix(value: string, nextTheme: MermaidTheme, mermaid: any) {
    if (getMermaidDiagramKind(value) === 'gantt') {
      const prefix = getSafeMermaidPrefixCandidate(value)
      if (!prefix.trim())
        return { fullOk: false, prefixOk: false }
      try {
        await canParseMermaid(prefix, nextTheme, mermaid)
        return prefix === value
          ? { fullOk: true, prefixOk: false }
          : { fullOk: false, prefixOk: true, prefix }
      }
      catch {
        return { fullOk: false, prefixOk: false }
      }
    }

    try {
      await canParseMermaid(value, nextTheme, mermaid)
      return { fullOk: true, prefixOk: false }
    }
    catch {
      // Try a renderable prefix below.
    }

    let prefix = getSafeMermaidPrefixCandidate(value)
    if (!prefix.trim() || prefix === value)
      return { fullOk: false, prefixOk: false }

    try {
      const workerPrefix = await findPrefixOffthread(value, nextTheme, workerTimeoutMs)
      if (workerPrefix?.trim())
        prefix = workerPrefix
    }
    catch {
      // Keep the local prefix.
    }

    try {
      await canParseMermaid(prefix, nextTheme, mermaid)
      return { fullOk: false, prefixOk: true, prefix }
    }
    catch {
      return { fullOk: false, prefixOk: false }
    }
  }

  function isGanttTaskLine(rawLine: string) {
    const line = rawLine.trim()
    if (!line || line.startsWith('%%'))
      return false
    if (/^(?:gantt|title|dateformat|axisformat|tickinterval|excludes|section|todaymarker|topaxis|weekday|weekend|acctitle|accdescr|accdescrmultiline)\b/i.test(line))
      return false
    return line.includes(':')
  }

  function getSafeGanttPreviewCandidate(value: string) {
    const lines = value.split(/\r?\n/)
    if (!/\r?\n$/.test(value) && lines.length > 0)
      lines.pop()
    while (lines.length > 0) {
      const last = lines[lines.length - 1]?.trim()
      if (!last || last.startsWith('%%')) {
        lines.pop()
        continue
      }
      if (isGanttTaskLine(last))
        break
      lines.pop()
    }
    return lines.some(isGanttTaskLine) ? lines.join('\n') : ''
  }

  function getSafeMermaidPrefixCandidate(value: string) {
    if (getMermaidDiagramKind(value) === 'gantt')
      return getSafeGanttPreviewCandidate(value)
    const lines = value.split('\n')
    while (lines.length > 0) {
      const last = (lines[lines.length - 1] || '').trimEnd()
      if (!last) {
        lines.pop()
        continue
      }
      const dangling = /^[-=~>|<\s]+$/.test(last.trim())
        || /(?:--|==|~~|->|<-|-\||-\)|-x|o-|\|-|\.-)\s*$/.test(last)
        || /[-|><]$/.test(last)
        || /(?:graph|flowchart|sequenceDiagram|classDiagram|stateDiagram|erDiagram|gantt)\s*$/i.test(last)
      if (!dangling)
        break
      lines.pop()
    }
    return lines.join('\n').trim() || ''
  }

  function normalizeRenderedCode(value: string) {
    return value.replace(/\s+/g, '')
  }

  function getRenderSignature() {
    return `${source}\n${theme}\n${isStrict}\n${enableMermaidInteractions}\n${final}\n${progressivePreview}`
  }

  function withTimeout<T>(run: () => Promise<T>, timeoutMs: number) {
    if (!timeoutMs || timeoutMs <= 0)
      return run()
    return new Promise<T>((resolve, reject) => {
      const timer = setTimeout(() => reject(new Error('Operation timed out')), timeoutMs)
      run().then((value) => {
        clearTimeout(timer)
        resolve(value)
      }).catch((error) => {
        clearTimeout(timer)
        reject(error)
      })
    })
  }

  function bindCurrentMermaidInteractions(element: Element | null | undefined) {
    if (!enableMermaidInteractions || !element?.querySelector('svg'))
      return
    try {
      lastMermaidBindFunctions?.(element)
    }
    catch {}
  }

  async function copy() {
    await copyTextToClipboard(source)
    context?.events?.onCopy?.(source)
    copied = true
    if (copyTimer)
      clearTimeout(copyTimer)
    copyTimer = setTimeout(() => {
      copied = false
    }, 1000)
  }

  function exportSvg() {
    if (svgMarkup)
      downloadSvgMarkup(svgMarkup, `mermaid-diagram-${Date.now()}.svg`)
  }

  function switchMode(mode: 'preview' | 'source') {
    showSource = mode === 'source'
    if (!showSource)
      void renderMermaid()
  }

  function zoomIn() {
    zoom = Math.min(3, Math.round((zoom + 0.1) * 10) / 10)
  }

  function zoomOut() {
    zoom = Math.max(0.5, Math.round((zoom - 0.1) * 10) / 10)
  }

  function resetZoom() {
    zoom = 1
    translateX = 0
    translateY = 0
  }

  // Drag functionality. The gesture lifecycle (window listeners, pointer identity,
  // lost releases) lives in markstream-core so every package pans identically.
  const panGesture = createPanGesture({
    getTranslate: () => ({ x: translateX, y: translateY }),
    setTranslate: (next) => {
      translateX = next.x
      translateY = next.y
    },
    canStart: (event) => {
      // Nothing to pan until the diagram exists. Without this the pending/error
      // source panel the block renders in the preview would be claimed by the
      // gesture, and `preventDefault` would take text selection away from it.
      if (!svgMarkup)
        return false

      // Touch pans only where the surface claims the gesture. Elsewhere the page
      // keeps the swipe for scrolling, and panning along with it would shift the
      // diagram by a few pixels before the browser takes the gesture over.
      return event.pointerType !== 'touch' || panSurfaceClaimsTouch
    },
    onActiveChange: active => (isDragging = active),
  })

  function startDrag(event: PointerEvent) {
    panGesture.start(event)
  }

  function showButtonTooltip(event: MouseEvent | FocusEvent, text: string, placement: TooltipPlacement = 'top') {
    const target = event.currentTarget as HTMLElement | null
    if (!target || (target instanceof HTMLButtonElement && target.disabled))
      return
    showTooltipForAnchor(target, text, placement, false, undefined, resolvedIsDark)
  }

  function showCopyTooltip(event: MouseEvent | FocusEvent) {
    showButtonTooltip(event, copied ? (t('common.copied') || 'Copied') : (t('common.copy') || 'Copy'))
  }

  function portal(node: HTMLElement) {
    document.body.appendChild(node)
    return {
      destroy() {
        node.remove()
      },
    }
  }

  function closeModal() {
    modalOpen = false
  }

  function onModalOverlayClick(event: MouseEvent) {
    if (event.target === event.currentTarget)
      closeModal()
  }

  function onModalKeydown(event: KeyboardEvent) {
    if (event.key === 'Escape')
      closeModal()
  }
</script>

{#if shouldRender}
  <div
    bind:this={blockHost}
    class:dark={resolvedIsDark}
    class:is-rendering={resolvedLoading || rendering}
    class="mermaid-block"
    data-markstream-mermaid="1"
    data-markstream-mode={showSource ? 'source' : canUsePreview ? 'preview' : 'fallback'}
  >
    {#if showHeader}
      <div class="mermaid-header">
        <div class="mermaid-header__title">
          <span class="icon-slot action-icon" aria-hidden="true">{@html mermaidIcon}</span>
          <span class="mermaid-title__text">Mermaid</span>
        </div>
        {#if showModeToggle}
          <div class="mermaid-toggle">
            <button type="button" class:mermaid-toggle-btn--active={!showSource} class="mermaid-toggle-btn" onblur={() => hideTooltip()} onclick={() => switchMode('preview')} onfocus={(event) => showButtonTooltip(event, t('common.preview') || 'Preview')} onmouseleave={() => hideTooltip()} onmouseenter={(event) => showButtonTooltip(event, t('common.preview') || 'Preview')}>
              <span class="mermaid-action-content">
                <svg aria-hidden="true" role="img" viewBox="0 0 24 24"><g fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"><path d="M2.062 12.348a1 1 0 0 1 0-.696a10.75 10.75 0 0 1 19.876 0a1 1 0 0 1 0 .696a10.75 10.75 0 0 1-19.876 0"/><circle cx="12" cy="12" r="3"/></g></svg>
                <span>{t('common.preview')}</span>
              </span>
            </button>
            <button type="button" class:mermaid-toggle-btn--active={showSource} class="mermaid-toggle-btn" onblur={() => hideTooltip()} onclick={() => switchMode('source')} onfocus={(event) => showButtonTooltip(event, t('common.source') || 'Source')} onmouseleave={() => hideTooltip()} onmouseenter={(event) => showButtonTooltip(event, t('common.source') || 'Source')}>
              <span class="mermaid-action-content">
                <svg aria-hidden="true" role="img" viewBox="0 0 24 24"><path fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m16 18l6-6l-6-6M8 6l-6 6l6 6"/></svg>
                <span>{t('common.source')}</span>
              </span>
            </button>
          </div>
        {/if}
        <div class="mermaid-actions">
          {#if showCollapseButton}
            <button type="button" class="mermaid-btn mermaid-action-btn mermaid-btn--icon" aria-pressed={collapsed} aria-label={collapsed ? t('common.expand') : t('common.collapse')} onblur={() => hideTooltip()} onclick={() => (collapsed = !collapsed)} onfocus={(event) => showButtonTooltip(event, collapsed ? (t('common.expand') || 'Expand') : (t('common.collapse') || 'Collapse'))} onmouseleave={() => hideTooltip()} onmouseenter={(event) => showButtonTooltip(event, collapsed ? (t('common.expand') || 'Expand') : (t('common.collapse') || 'Collapse'))}>
              <svg style:rotate={collapsed ? '0deg' : '90deg'} viewBox="0 0 24 24" aria-hidden="true"><path fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m9 18l6-6l-6-6" /></svg>
            </button>
          {/if}
          {#if showCopyButton}
            <button type="button" class="mermaid-btn mermaid-action-btn mermaid-btn--icon" aria-label={copied ? t('common.copied') : t('common.copy')} onblur={() => hideTooltip()} onclick={copy} onfocus={showCopyTooltip} onmouseleave={() => hideTooltip()} onmouseenter={showCopyTooltip}>
              {#if copied}
                <svg aria-hidden="true" role="img" viewBox="0 0 24 24"><path fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M20 6L9 17l-5-5"/></svg>
              {:else}
                <svg aria-hidden="true" role="img" viewBox="0 0 24 24"><g fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"><rect width="14" height="14" x="8" y="8" rx="2" ry="2"/><path d="M4 16c-1.1 0-2-.9-2-2V4c0-1.1.9-2 2-2h10c1.1 0 2 .9 2 2"/></g></svg>
              {/if}
            </button>
          {/if}
          {#if showExportButton}
            <button type="button" class="mermaid-btn mermaid-action-btn mermaid-btn--icon" aria-label={t('common.export')} disabled={!svgMarkup || showSource || collapsed} onblur={() => hideTooltip()} onclick={exportSvg} onfocus={(event) => showButtonTooltip(event, t('common.export') || 'Export')} onmouseleave={() => hideTooltip()} onmouseenter={(event) => showButtonTooltip(event, t('common.export') || 'Export')}>
              <svg aria-hidden="true" role="img" viewBox="0 0 24 24"><g fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"><path d="M12 15V3m9 12v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"/><path d="m7 10l5 5l5-5"/></g></svg>
            </button>
          {/if}
          {#if showFullscreenButton}
            <button type="button" class="mermaid-btn mermaid-action-btn mermaid-btn--icon" aria-label={t('common.open')} disabled={!svgMarkup || showSource || collapsed} onblur={() => hideTooltip()} onclick={() => (modalOpen = true)} onfocus={(event) => showButtonTooltip(event, t('common.open') || 'Open')} onmouseleave={() => hideTooltip()} onmouseenter={(event) => showButtonTooltip(event, t('common.open') || 'Open')}>
              <svg aria-hidden="true" role="img" viewBox="0 0 24 24"><path fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 3h6v6m0-6l-7 7M3 21l7-7m-1 7H3v-6"/></svg>
            </button>
          {/if}
        </div>
      </div>
    {/if}

    {#if !collapsed}
      <div class="mermaid-body">
        {#if showSource}
          <pre class="mermaid-source"><code>{source}</code></pre>
        {:else}
          {#if showZoomControls}
            <div class="markstream-svelte-zoom-controls">
              <button type="button" class="mermaid-btn mermaid-action-btn mermaid-btn--icon" aria-label={t('common.zoomIn')} onblur={() => hideTooltip()} onclick={zoomIn} onfocus={(event) => showButtonTooltip(event, t('common.zoomIn') || 'Zoom in')} onmouseleave={() => hideTooltip()} onmouseenter={(event) => showButtonTooltip(event, t('common.zoomIn') || 'Zoom in')}>
                <svg aria-hidden="true" role="img" viewBox="0 0 24 24"><g fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"><circle cx="11" cy="11" r="8"/><path d="m21 21l-4.35-4.35M11 8v6m-3-3h6"/></g></svg>
              </button>
              <button type="button" class="mermaid-btn mermaid-action-btn mermaid-btn--icon" aria-label={t('common.zoomOut')} onblur={() => hideTooltip()} onclick={zoomOut} onfocus={(event) => showButtonTooltip(event, t('common.zoomOut') || 'Zoom out')} onmouseleave={() => hideTooltip()} onmouseenter={(event) => showButtonTooltip(event, t('common.zoomOut') || 'Zoom out')}>
                <svg aria-hidden="true" role="img" viewBox="0 0 24 24"><g fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"><circle cx="11" cy="11" r="8"/><path d="m21 21l-4.35-4.35M8 11h6"/></g></svg>
              </button>
              <button type="button" class="mermaid-btn mermaid-action-btn mermaid-zoom-reset" aria-label={t('common.resetZoom')} onblur={() => hideTooltip()} onclick={resetZoom} onfocus={(event) => showButtonTooltip(event, t('common.resetZoom') || 'Reset zoom')} onmouseleave={() => hideTooltip()} onmouseenter={(event) => showButtonTooltip(event, t('common.resetZoom') || 'Reset zoom')}>{Math.round(zoom * 100)}%</button>
            </div>
          {/if}
          <!-- svelte-ignore a11y_no_static_element_interactions -->
          <div bind:this={previewHost} class="mermaid-preview markstream-svelte-mermaid" class:markstream-svelte-pan-touch={panSurfaceClaimsTouch} style={previewStyle} onpointerdown={startDrag}>
            {#if svgMarkup}
              {@html svgMarkup}
            {:else if renderError}
              <pre class="mermaid-source"><code>{source}</code></pre>
            {:else}
              <div class="mermaid-loading"><span class="mermaid-spinner"></span> {t('common.preview')}</div>
            {/if}
          </div>
          {#if renderError}
            <div class="mermaid-error">{renderError}</div>
          {/if}
        {/if}
      </div>
    {/if}

    {#if modalOpen}
      <div use:portal class:dark={resolvedIsDark} class="markstream-svelte markstream-svelte-modal-root">
        <div class="mermaid-modal-overlay" role="dialog" aria-modal="true" tabindex="-1" onclick={onModalOverlayClick} onkeydown={onModalKeydown}>
          <div class="mermaid-modal-panel">
            <div class="mermaid-modal-controls">
              <button type="button" class="mermaid-btn mermaid-action-btn mermaid-btn--icon" aria-label={t('common.zoomIn')} onclick={zoomIn}>
                <svg aria-hidden="true" role="img" viewBox="0 0 24 24"><g fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"><circle cx="11" cy="11" r="8"/><path d="m21 21l-4.35-4.35M11 8v6m-3-3h6"/></g></svg>
              </button>
              <button type="button" class="mermaid-btn mermaid-action-btn mermaid-btn--icon" aria-label={t('common.zoomOut')} onclick={zoomOut}>
                <svg aria-hidden="true" role="img" viewBox="0 0 24 24"><g fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"><circle cx="11" cy="11" r="8"/><path d="m21 21l-4.35-4.35M8 11h6"/></g></svg>
              </button>
              <button type="button" class="mermaid-btn mermaid-action-btn mermaid-zoom-reset" aria-label={t('common.resetZoom')} onclick={resetZoom}>{Math.round(zoom * 100)}%</button>
              <button type="button" class="mermaid-btn mermaid-action-btn mermaid-btn--icon" aria-label={t('common.close')} onclick={closeModal}>
                <svg aria-hidden="true" role="img" viewBox="0 0 24 24"><path fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M18 6L6 18M6 6l12 12"/></svg>
              </button>
            </div>
            <!-- svelte-ignore a11y_no_static_element_interactions -->
            <div class="mermaid-modal-body" class:markstream-svelte-pan-touch={panSurfaceClaimsTouch} style={`cursor: ${isDragging ? 'grabbing' : 'grab'}`} onpointerdown={startDrag}>
              <div bind:this={modalHost} class="mermaid-modal-content markstream-svelte-mermaid" style={`transform: translate(${translateX}px, ${translateY}px) scale(${zoom});`}>{@html svgMarkup}</div>
            </div>
          </div>
        </div>
      </div>
    {/if}
  </div>
{/if}

// packages/markstream-angular/src/components/MermaidBlockNode/MermaidBlockNode.component.ts
import type { AfterViewInit, ElementRef, OnChanges, OnDestroy } from '@angular/core'
import type { AngularRenderableNode, AngularRenderContext } from '../shared/node-helpers'
import { CommonModule } from '@angular/common'
import {
  ChangeDetectionStrategy,
  ChangeDetectorRef,
  Component,
  HostListener,
  inject,
  Input,
  ViewChild,
} from '@angular/core'
import { createPanGesture } from 'markstream-core'
import { toSafeMermaidSvgMarkup } from 'stream-markdown-parser'
import { getMermaid } from '../../optional/mermaid'
import { createMermaidRenderId } from '../../utils/mermaidRenderId'
import { canParseOffthread, findPrefixOffthread } from '../../workers/mermaidWorkerClient'
import { clampPreviewHeight, estimateMermaidPreviewHeight, MERMAID_PREVIEW_MIN_HEIGHT, parsePositiveNumber } from '../shared/diagram-height'
import { getString } from '../shared/node-helpers'
import {
  clampNumber,
  copyTextToClipboard,
  downloadSvgMarkup,
  resolveCssSize,
  setElementHtml,
} from '../shared/rich-block-helpers'

let mermaidRenderQueue: Promise<void> = Promise.resolve()

type MermaidTheme = 'light' | 'dark'
type MermaidBindFunctions = (element: Element) => unknown

function enqueueMermaidRender<T>(run: () => Promise<T>) {
  const next = mermaidRenderQueue.then(run, run)
  mermaidRenderQueue = next.then(() => undefined, () => undefined)
  return next
}

@Component({
  selector: 'markstream-angular-mermaid-block-node',
  standalone: true,
  imports: [CommonModule],
  template: `
    <div
      class="mermaid-block"
      [class.dark]="resolvedIsDark"
      [attr.data-markstream-mermaid]="'1'"
      [attr.data-mode]="showSource ? 'source' : 'preview'"
    >
      <div *ngIf="resolvedShowHeader" class="mermaid-header">
        <div class="flex items-center gap-2 min-w-0">
          <span class="markstream-angular-enhanced-block__badge">Mermaid</span>
          <span class="mermaid-title__text truncate">Diagram</span>
        </div>

        <div class="mermaid-actions">
          <div *ngIf="resolvedShowModeToggle" class="mermaid-toggle" role="tablist" aria-label="Mermaid mode">
            <button
              type="button"
              class="mermaid-toggle-btn"
              [class.mermaid-toggle-btn--active]="!showSource"
              [attr.aria-pressed]="!showSource"
              (click)="setMode(false)"
            >
              Preview
            </button>
            <button
              type="button"
              class="mermaid-toggle-btn"
              [class.mermaid-toggle-btn--active]="showSource"
              [attr.aria-pressed]="showSource"
              (click)="setMode(true)"
            >
              Source
            </button>
          </div>

          <button
            *ngIf="resolvedShowCopyButton"
            type="button"
            class="mermaid-btn"
            [attr.title]="tooltipFor(copied ? 'Copied' : 'Copy')"
            (click)="copySource()"
          >
            {{ copied ? 'Copied' : 'Copy' }}
          </button>

          <button
            *ngIf="resolvedShowExportButton"
            type="button"
            class="mermaid-btn"
            [disabled]="!svgMarkup"
            [attr.title]="tooltipFor('Export SVG')"
            (click)="exportSvg()"
          >
            Export
          </button>

          <button
            *ngIf="resolvedShowFullscreenButton"
            type="button"
            class="mermaid-btn"
            [disabled]="!svgMarkup"
            [attr.title]="tooltipFor('Fullscreen')"
            (click)="openModal()"
          >
            Fullscreen
          </button>

          <button
            *ngIf="resolvedShowCollapseButton"
            type="button"
            class="mermaid-btn"
            [attr.title]="tooltipFor(collapsed ? 'Expand' : 'Collapse')"
            (click)="toggleCollapsed()"
          >
            {{ collapsed ? 'Expand' : 'Collapse' }}
          </button>

          <ng-container *ngIf="resolvedShowZoomControls && !showSource && !collapsed">
            <button type="button" class="mermaid-btn" [attr.title]="tooltipFor('Zoom out')" (click)="adjustZoom(-0.1)">-</button>
            <button type="button" class="mermaid-btn" [attr.title]="tooltipFor('Reset zoom')" (click)="resetZoom()">100%</button>
            <button type="button" class="mermaid-btn" [attr.title]="tooltipFor('Zoom in')" (click)="adjustZoom(0.1)">+</button>
          </ng-container>
        </div>
      </div>

      <div *ngIf="!collapsed" class="mermaid-body">
        <div *ngIf="rendering && !showSource" class="mermaid-loading">
          <span class="mermaid-spinner" aria-hidden="true"></span>
          <span>Rendering Mermaid...</span>
        </div>

        <div
          *ngIf="!showSource"
          class="mermaid-preview"
          [style.maxHeight]="resolvedMaxHeight"
          [style.minHeight.px]="estimatedPreviewHeightPx"
          [style.height.px]="estimatedPreviewHeightPx"
          [style.transform]="previewTransform"
          [style.touch-action]="panSurfaceClaimsTouch ? 'none' : null"
          [style.cursor]="isDragging ? 'grabbing' : 'grab'"
          (pointerdown)="onPanStart($event)"
        >
          <div #previewHost class="markstream-angular-mermaid" [class.is-empty]="!svgMarkup"></div>
        </div>

        <pre *ngIf="showSource" class="mermaid-source"><code translate="no">{{ code }}</code></pre>

        <div *ngIf="error" class="mermaid-error">{{ error }}</div>
      </div>

      <span class="sr-only" aria-live="polite" role="status">{{ copied ? 'Copied' : '' }}</span>
    </div>

    <div
      *ngIf="modalOpen"
      class="mermaid-modal-overlay"
      role="dialog"
      aria-modal="true"
      (click)="closeModal()"
    >
      <div
        class="mermaid-modal-panel"
        [class.is-dark]="resolvedIsDark"
        (click)="$event.stopPropagation()"
      >
        <div class="mermaid-modal-header">
          <span class="mermaid-modal-title">Mermaid Preview</span>
          <button type="button" class="mermaid-modal-close" (click)="closeModal()">Close</button>
        </div>
        <div class="mermaid-modal-body">
          <div
            class="mermaid-modal-content"
            [style.transform]="modalTransform"
            [style.touch-action]="panSurfaceClaimsTouch ? 'none' : null"
            [style.cursor]="isDragging ? 'grabbing' : 'grab'"
            (pointerdown)="onPanStart($event)"
            (wheel)="handleModalWheel($event)"
          >
            <div #modalHost class="markstream-angular-mermaid fullscreen"></div>
          </div>
        </div>
      </div>
    </div>
  `,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class MermaidBlockNodeComponent implements AfterViewInit, OnChanges, OnDestroy {
  private readonly cdr = inject(ChangeDetectorRef)

  @ViewChild('previewHost') private previewHost?: ElementRef<HTMLElement>
  @ViewChild('modalHost') private modalHost?: ElementRef<HTMLElement>

  @Input({ required: true }) node!: AngularRenderableNode
  @Input() context?: AngularRenderContext
  @Input() props?: Record<string, any>

  rendering = false
  copied = false
  collapsed = false
  showSource = false
  modalOpen = false
  zoom = 1
  translateX = 0
  translateY = 0
  isDragging = false
  svgMarkup = ''
  error = ''

  private viewReady = false
  private destroyed = false
  private renderToken = 0
  private copyTimer: number | null = null
  private lastMermaidBindFunctions: MermaidBindFunctions | null = null

  // Drag functionality. The gesture lifecycle (window listeners, pointer identity,
  // lost releases) lives in markstream-core so every package pans identically.
  private readonly panGesture = createPanGesture({
    getTranslate: () => ({ x: this.translateX, y: this.translateY }),
    setTranslate: (next) => {
      this.translateX = next.x
      this.translateY = next.y
      this.cdr.markForCheck()
    },
    canStart: (event) => {
      // Nothing to pan until the diagram exists. Without this the error message the
      // block renders in the preview would be claimed by the gesture, and
      // `preventDefault` would take text selection away from it.
      if (!this.hasDiagramSvg())
        return false

      // Touch pans only where the surface claims the gesture. Elsewhere the page
      // keeps the swipe for scrolling, and panning along with it would shift the
      // diagram by a few pixels before the browser takes the gesture over.
      return event.pointerType !== 'touch' || this.panSurfaceClaimsTouch
    },
    onActiveChange: (active) => {
      this.isDragging = active
      this.cdr.markForCheck()
    },
  })

  get mergedProps() {
    return {
      ...(this.context?.mermaidProps || {}),
      ...(this.props || {}),
    }
  }

  get code() {
    return getString((this.node as any)?.code)
      .replace(/\]::([^:])/g, ']:::$1')
      .replace(/:::subgraphNode$/gm, '::subgraphNode')
  }

  get resolvedIsDark() {
    if (typeof this.mergedProps.isDark === 'boolean')
      return this.mergedProps.isDark
    return this.context?.isDark === true
  }

  get resolvedShowHeader() {
    return this.mergedProps.showHeader !== false
  }

  get resolvedShowModeToggle() {
    return this.mergedProps.showModeToggle !== false
  }

  get resolvedShowCopyButton() {
    return this.mergedProps.showCopyButton !== false
  }

  get resolvedShowExportButton() {
    return this.mergedProps.showExportButton !== false
  }

  get resolvedShowFullscreenButton() {
    return this.mergedProps.showFullscreenButton !== false
  }

  get resolvedShowCollapseButton() {
    return this.mergedProps.showCollapseButton !== false
  }

  get resolvedShowZoomControls() {
    return this.mergedProps.showZoomControls !== false
  }

  get resolvedShowTooltips() {
    if (typeof this.mergedProps.showTooltips === 'boolean')
      return this.mergedProps.showTooltips
    return this.context?.showTooltips !== false
  }

  get resolvedMaxHeight() {
    return resolveCssSize(this.mergedProps.maxHeight, '500px')
  }

  get estimatedPreviewHeightPx() {
    return clampPreviewHeight(
      parsePositiveNumber(this.mergedProps.estimatedPreviewHeightPx) ?? estimateMermaidPreviewHeight(this.code),
      this.resolveDiagramMinHeight(),
      this.maxPreviewHeight,
    )
  }

  /**
   * Resolve the diagram preview minimum height from the density CSS token
   * (--ms-size-diagram-min-height), falling back to the built-in default.
   * Mirrors the vue3 renderer's resolveMinContainerHeight; SSR falls back to
   * the constant because getComputedStyle is browser-only.
   */
  private resolveDiagramMinHeight() {
    const el = this.previewHost?.nativeElement
    if (!el || typeof window === 'undefined' || typeof window.getComputedStyle !== 'function')
      return MERMAID_PREVIEW_MIN_HEIGHT
    const raw = window.getComputedStyle(el).getPropertyValue('--ms-size-diagram-min-height').trim()
    return parsePositiveNumber(raw) ?? MERMAID_PREVIEW_MIN_HEIGHT
  }

  private get maxPreviewHeight() {
    if (this.mergedProps.maxHeight == null || this.mergedProps.maxHeight === 'none')
      return this.mergedProps.maxHeight === 'none' ? null : 500
    return parsePositiveNumber(this.mergedProps.maxHeight) ?? 500
  }

  get resolvedWorkerTimeout() {
    return clampNumber(Number(this.mergedProps.workerTimeoutMs ?? 1400), 200, 10_000)
  }

  get resolvedParseTimeout() {
    return clampNumber(Number(this.mergedProps.parseTimeoutMs ?? 1800), 200, 10_000)
  }

  get resolvedRenderTimeout() {
    return clampNumber(Number(this.mergedProps.renderTimeoutMs ?? 2500), 200, 15_000)
  }

  get resolvedFullRenderTimeout() {
    return clampNumber(Number(this.mergedProps.fullRenderTimeoutMs ?? 4000), 200, 20_000)
  }

  get strictMode() {
    return this.mergedProps.isStrict !== false
  }

  get resolvedLoading() {
    if (typeof this.mergedProps.loading === 'boolean')
      return this.mergedProps.loading
    return (this.node as any)?.loading === true
  }

  get resolvedProgressiveRender() {
    return this.mergedProps.progressiveRender === true
  }

  /**
   * The diagram is scaled to fit the preview box, so at fit zoom nothing is
   * off-screen and panning only shifts it inside the box. Touch therefore keeps
   * scrolling the page at that zoom (a chat is mostly scrolling) and only claims
   * the gesture once the diagram is zoomed in and actually overflows the box.
   * The fullscreen modal always claims it: the surface fills the viewport, panning
   * is the intended gesture there, and the page behind it is locked anyway.
   */
  get panSurfaceClaimsTouch() {
    return this.modalOpen || this.zoom > 1
  }

  get previewTransform() {
    return `translate(${this.translateX}px, ${this.translateY}px) scale(${this.zoom})`
  }

  get modalTransform() {
    return `translate(${this.translateX}px, ${this.translateY}px) scale(${Math.max(1, this.zoom)})`
  }

  /**
   * Whether a pan surface holds a rendered diagram. The modal renders its own
   * copy of the SVG, so it is checked as well: the source panel may have taken
   * the inline preview's place while the modal is open.
   */
  private hasDiagramSvg() {
    return !!this.previewHost?.nativeElement?.querySelector('svg')
      || !!this.modalHost?.nativeElement?.querySelector('svg')
  }

  ngAfterViewInit() {
    this.viewReady = true
    queueMicrotask(() => void this.renderDiagram())
  }

  ngOnChanges() {
    if (!this.viewReady)
      return
    queueMicrotask(() => void this.renderDiagram())
  }

  ngOnDestroy() {
    this.destroyed = true
    this.renderToken += 1
    this.panGesture.stop()
    if (this.copyTimer != null && typeof window !== 'undefined')
      window.clearTimeout(this.copyTimer)
  }

  @HostListener('window:keydown', ['$event'])
  handleWindowKeydown(event: KeyboardEvent) {
    if (event.key === 'Escape' && this.modalOpen)
      this.closeModal()
  }

  tooltipFor(text: string) {
    return this.resolvedShowTooltips ? text : null
  }

  setMode(nextSource: boolean) {
    this.showSource = nextSource
    if (!nextSource)
      this.scheduleHostSync()
    this.cdr.markForCheck()
  }

  async copySource() {
    await copyTextToClipboard(this.code)
    this.copied = true
    this.context?.events.onCopy?.(this.code)
    if (this.copyTimer != null && typeof window !== 'undefined')
      window.clearTimeout(this.copyTimer)
    if (typeof window !== 'undefined') {
      this.copyTimer = window.setTimeout(() => {
        this.copied = false
        this.cdr.markForCheck()
      }, 1000)
    }
    this.cdr.markForCheck()
  }

  exportSvg() {
    if (!this.svgMarkup)
      return
    downloadSvgMarkup(this.svgMarkup, `mermaid-${Date.now()}.svg`)
  }

  openModal() {
    if (!this.svgMarkup)
      return
    this.modalOpen = true
    if (typeof document !== 'undefined')
      document.body.style.overflow = 'hidden'
    queueMicrotask(() => this.syncSvgHosts())
    this.cdr.markForCheck()
  }

  closeModal() {
    this.modalOpen = false
    if (typeof document !== 'undefined')
      document.body.style.overflow = ''
    this.cdr.markForCheck()
  }

  toggleCollapsed() {
    this.collapsed = !this.collapsed
    if (!this.collapsed)
      queueMicrotask(() => void this.renderDiagram())
    this.cdr.markForCheck()
  }

  adjustZoom(delta: number) {
    this.zoom = clampNumber(Number((this.zoom + delta).toFixed(2)), 0.4, 2.5)
    this.cdr.markForCheck()
  }

  resetZoom() {
    this.zoom = 1
    this.translateX = 0
    this.translateY = 0
    this.cdr.markForCheck()
  }

  onPanStart(event: PointerEvent) {
    this.panGesture.start(event)
  }

  handleModalWheel(event: WheelEvent) {
    if (this.mergedProps.enableWheelZoom !== true)
      return
    event.preventDefault()
    this.adjustZoom(event.deltaY > 0 ? -0.08 : 0.08)
  }

  private async renderDiagram() {
    if (this.destroyed || !this.viewReady || this.collapsed)
      return

    const source = this.code.trim()
    if (!source) {
      this.svgMarkup = ''
      this.error = ''
      this.syncSvgHosts()
      this.cdr.markForCheck()
      return
    }

    if (this.resolvedLoading && !this.resolvedProgressiveRender) {
      this.renderToken += 1
      this.rendering = true
      this.error = ''
      this.svgMarkup = ''
      this.syncSvgHosts()
      this.cdr.markForCheck()
      return
    }

    const token = ++this.renderToken
    this.rendering = true
    this.error = ''
    this.cdr.markForCheck()

    try {
      const mermaid = await getMermaid(this.strictMode
        ? {
            startOnLoad: false,
            securityLevel: 'strict',
            suppressErrorRendering: true,
            flowchart: { htmlLabels: false },
          }
        : {
            startOnLoad: false,
            securityLevel: 'loose',
            suppressErrorRendering: true,
          })

      if (!mermaid)
        throw new Error('Mermaid renderer is not available.')

      const theme: MermaidTheme = this.resolvedIsDark ? 'dark' : 'light'
      let renderSource = source
      if (this.resolvedLoading && this.resolvedProgressiveRender) {
        try {
          const res = await this.canParseOrPrefix(source, theme, mermaid, token)
          if (this.destroyed || token !== this.renderToken)
            return
          if (!res.fullOk && !res.prefix) {
            this.rendering = false
            this.cdr.markForCheck()
            return
          }
          if (res.prefix)
            renderSource = res.prefix
        }
        catch (error: any) {
          if (error?.name === 'AbortError')
            return
          this.rendering = false
          this.cdr.markForCheck()
          return
        }
      }

      const renderId = createMermaidRenderId()
      const themedSource = this.applyThemeTo(renderSource, theme)
      const rendered = await enqueueMermaidRender(() => this.withTimeout(
        () => Promise.resolve(mermaid.render(renderId, themedSource)),
        this.resolvedLoading && this.resolvedProgressiveRender
          ? this.resolvedRenderTimeout
          : this.resolvedFullRenderTimeout,
      ))
      if (this.destroyed || token !== this.renderToken)
        return

      const svg = typeof rendered === 'string' ? rendered : rendered?.svg
      const safeSvg = toSafeMermaidSvgMarkup(svg)
      if (!safeSvg)
        throw new Error('Mermaid produced invalid SVG during preview')

      this.svgMarkup = safeSvg
      this.lastMermaidBindFunctions = typeof rendered === 'string' ? null : rendered?.bindFunctions ?? null
      if (!this.svgMarkup)
        this.showSource = true
      this.syncSvgHosts()
    }
    catch (error) {
      if (this.destroyed || token !== this.renderToken)
        return
      if (this.resolvedLoading && this.resolvedProgressiveRender) {
        this.svgMarkup = ''
        this.syncSvgHosts()
        return
      }
      // Allow consumer to handle the error via onRenderError callback
      const onRenderError = this.mergedProps.onRenderError
      if (typeof onRenderError === 'function' && this.previewHost?.nativeElement) {
        const handled = onRenderError(error, this.code, this.previewHost.nativeElement)
        if (handled === true) {
          this.svgMarkup = ''
          return
        }
      }
      this.svgMarkup = ''
      this.showSource = true
      this.error = error instanceof Error ? error.message : 'Failed to render Mermaid diagram.'
      this.syncSvgHosts()
    }
    finally {
      if (token === this.renderToken) {
        this.rendering = false
        this.cdr.markForCheck()
      }
    }
  }

  private syncSvgHosts() {
    setElementHtml(this.previewHost?.nativeElement, this.svgMarkup)
    if (this.modalOpen)
      setElementHtml(this.modalHost?.nativeElement, this.svgMarkup)
    else
      setElementHtml(this.modalHost?.nativeElement, '')
    this.bindMermaidInteractions(this.previewHost?.nativeElement)
    if (this.modalOpen)
      this.bindMermaidInteractions(this.modalHost?.nativeElement)
  }

  private bindMermaidInteractions(element: Element | null | undefined) {
    if (this.mergedProps.enableMermaidInteractions !== true || !this.svgMarkup || !element?.querySelector('svg'))
      return
    try {
      this.lastMermaidBindFunctions?.(element)
    }
    catch {}
  }

  private scheduleHostSync() {
    if (typeof window !== 'undefined') {
      window.setTimeout(() => {
        if (this.destroyed)
          return
        this.syncSvgHosts()
        this.cdr.markForCheck()
      }, 0)
      return
    }
    queueMicrotask(() => this.syncSvgHosts())
  }

  private async canParseWithFallback(source: string, theme: MermaidTheme, mermaid: any, token: number) {
    try {
      const canParse = await canParseOffthread(source, theme, this.resolvedWorkerTimeout)
      if (this.destroyed || token !== this.renderToken)
        throw new DOMException('Aborted', 'AbortError')
      if (canParse)
        return true
    }
    catch (error: any) {
      if (error?.name === 'AbortError')
        throw error
    }

    const themedSource = this.applyThemeTo(source, theme)
    const anyMermaid = mermaid as any
    if (typeof anyMermaid.parse === 'function') {
      await this.withTimeout(() => Promise.resolve(anyMermaid.parse(themedSource)), this.resolvedParseTimeout)
      if (this.destroyed || token !== this.renderToken)
        throw new DOMException('Aborted', 'AbortError')
      return true
    }

    const renderId = createMermaidRenderId('markstream-angular-mermaid-parse')
    await this.withTimeout(() => Promise.resolve(anyMermaid.render(renderId, themedSource)), this.resolvedParseTimeout)
    if (this.destroyed || token !== this.renderToken)
      throw new DOMException('Aborted', 'AbortError')
    return true
  }

  private async canParseOrPrefix(source: string, theme: MermaidTheme, mermaid: any, token: number) {
    if (this.getMermaidDiagramKind(source) === 'gantt') {
      const prefix = this.getSafePrefixCandidate(source)
      if (!prefix.trim())
        return { fullOk: false, prefix: '' }
      await this.canParseWithFallback(prefix, theme, mermaid, token)
      if (this.destroyed || token !== this.renderToken)
        throw new DOMException('Aborted', 'AbortError')
      return prefix === source ? { fullOk: true, prefix: '' } : { fullOk: false, prefix }
    }

    try {
      await this.canParseWithFallback(source, theme, mermaid, token)
      return { fullOk: true, prefix: '' }
    }
    catch (error: any) {
      if (error?.name === 'AbortError')
        throw error
    }

    const prefix = await this.findPrefixCandidate(source, theme, token)
    if (!prefix)
      return { fullOk: false, prefix: '' }
    await this.canParseWithFallback(prefix, theme, mermaid, token)
    if (this.destroyed || token !== this.renderToken)
      throw new DOMException('Aborted', 'AbortError')
    return { fullOk: false, prefix }
  }

  private async findPrefixCandidate(source: string, theme: MermaidTheme, token: number) {
    try {
      const prefix = await findPrefixOffthread(source, theme, this.resolvedWorkerTimeout)
      if (this.destroyed || token !== this.renderToken)
        throw new DOMException('Aborted', 'AbortError')
      if (prefix)
        return prefix
    }
    catch (error: any) {
      if (error?.name === 'AbortError')
        throw error
    }

    return this.getSafePrefixCandidate(source)
  }

  private applyThemeTo(source: string, theme: MermaidTheme) {
    const trimmed = source.trimStart()
    if (trimmed.startsWith('%%{'))
      return source
    const themeValue = theme === 'dark' ? 'dark' : 'default'
    return `%%{init: {"theme": "${themeValue}"}}%%\n${source}`
  }

  private getMermaidDiagramKind(source: string) {
    for (const rawLine of source.split(/\r?\n/)) {
      const line = rawLine.trim()
      if (!line || line.startsWith('%%'))
        continue
      const match = line.match(/^([A-Z][\w-]*)\b/i)
      return match?.[1]?.toLowerCase() || ''
    }
    return ''
  }

  private isGanttTaskLine(rawLine: string) {
    const line = rawLine.trim()
    if (!line || line.startsWith('%%'))
      return false
    if (/^(?:gantt|title|dateformat|axisformat|tickinterval|excludes|section|todaymarker|topaxis|weekday|weekend|acctitle|accdescr|accdescrmultiline)\b/i.test(line))
      return false
    return line.includes(':')
  }

  private getSafeGanttPreviewCandidate(source: string) {
    const lines = source.split(/\r?\n/)
    if (!/\r?\n$/.test(source) && lines.length > 0)
      lines.pop()
    while (lines.length > 0) {
      const last = lines[lines.length - 1]?.trim()
      if (!last || last.startsWith('%%')) {
        lines.pop()
        continue
      }
      if (this.isGanttTaskLine(last))
        break
      lines.pop()
    }
    return lines.some(line => this.isGanttTaskLine(line)) ? lines.join('\n') : ''
  }

  private getSafePrefixCandidate(source: string) {
    if (this.getMermaidDiagramKind(source) === 'gantt')
      return this.getSafeGanttPreviewCandidate(source)
    const lines = source.split('\n')
    while (lines.length > 0) {
      const lastRaw = lines[lines.length - 1]
      const last = lastRaw.trimEnd()
      if (!last) {
        lines.pop()
        continue
      }

      const looksDangling = /^[-=~>|<\s]+$/.test(last.trim())
        || /(?:--|==|~~|->|<-|-\||-\)|-x|o-|\|-|\.-)\s*$/.test(last)
        || /[-|><]$/.test(last)
        || /(?:graph|flowchart|sequenceDiagram|classDiagram|stateDiagram|erDiagram|gantt)\s*$/i.test(last)
      if (!looksDangling)
        break

      lines.pop()
    }
    return lines.join('\n')
  }

  private withTimeout<T>(run: () => Promise<T>, timeoutMs: number) {
    return new Promise<T>((resolve, reject) => {
      let settled = false
      const timer = typeof window !== 'undefined'
        ? window.setTimeout(() => {
            if (settled)
              return
            settled = true
            reject(new Error('Operation timed out'))
          }, timeoutMs)
        : null

      run()
        .then((value) => {
          if (settled)
            return
          settled = true
          if (timer != null && typeof window !== 'undefined')
            window.clearTimeout(timer)
          resolve(value)
        })
        .catch((error) => {
          if (settled)
            return
          settled = true
          if (timer != null && typeof window !== 'undefined')
            window.clearTimeout(timer)
          reject(error)
        })
    })
  }
}
