// packages/markstream-svelte/src/components/TextNode.svelte
<script lang="ts">
  import type { SvelteRenderableNode, SvelteRenderContext } from './shared/node-helpers'
  import { resolveStreamingTextState } from 'markstream-core'
  import { getString } from './shared/node-helpers'

  interface Props {
    node: SvelteRenderableNode
    context?: SvelteRenderContext
    indexKey?: string | number
    typewriter?: boolean
  }

  let {
    node,
    context = undefined,
    indexKey = undefined,
    typewriter = undefined
  }: Props = $props()

  let previousKey = ''
  let previousContent = ''
  let deltaClass = 'markstream-svelte-text__stream-delta--a'

  const content = $derived(getString((node as any)?.content ?? (node as any)?.raw))
  const centered = $derived(Boolean((node as any)?.center))
  const streamKey = $derived(String(context?.customId ?? 'global') + ':' + String(context?.streamRenderVersion ?? 0) + ':' + String(indexKey ?? 'node'))
  const fadeEnabled = $derived(context?.fade !== false)

  const streamInfo = $derived.by(() => {
    const state = context?.textStreamState
    const previous = streamKey === previousKey ? previousContent : (state?.get(streamKey) ?? '')

    const result = resolveStreamingTextState({
      nextContent: content,
      previousContent: previous,
      typewriterEnabled: fadeEnabled,
    })

    if (result.appended)
      deltaClass = deltaClass.endsWith('--a') ? 'markstream-svelte-text__stream-delta--b' : 'markstream-svelte-text__stream-delta--a'

    previousKey = streamKey
    previousContent = content
    state?.set(streamKey, content)

    return { stableContent: result.settledContent, deltaContent: result.streamedDelta, deltaClass }
  })
</script>

<span data-typewriter={context?.typewriter === true ? '1' : undefined} class:markstream-svelte-text--centered={centered} class="markstream-svelte-text-node text-node">{streamInfo.stableContent}{#if streamInfo.deltaContent}<span class="markstream-svelte-text__stream-delta text-node-stream-delta {streamInfo.deltaClass}">{streamInfo.deltaContent}</span>{/if}</span>

// packages/markstream-solid/src/components/TextNode.tsx
import type { SolidRenderableNode, SolidRenderContext } from '../node-helpers'
import { resolveStreamingTextState } from 'markstream-core'
import { createMemo } from 'solid-js'
import { getString } from '../node-helpers'

export interface TextNodeProps {
  node: SolidRenderableNode
  context?: SolidRenderContext
  indexKey?: string | number
  typewriter?: boolean
}

export function TextNode(props: TextNodeProps) {
  let previousKey = ''
  let previousContent = ''
  let deltaClass = 'markstream-solid-text__stream-delta--a'
  const streamInfo = createMemo(() => {
    const content = getString((props.node as any)?.content ?? (props.node as any)?.raw)
    const key = `${props.context?.customId ?? 'global'}:${props.context?.streamRenderVersion ?? 0}:${props.indexKey ?? 'node'}`
    const previous = key === previousKey ? previousContent : (props.context?.textStreamState?.get(key) ?? '')
    const result = resolveStreamingTextState({ nextContent: content, previousContent: previous, typewriterEnabled: props.context?.fade !== false })
    if (result.appended)
      deltaClass = deltaClass.endsWith('--a') ? 'markstream-solid-text__stream-delta--b' : 'markstream-solid-text__stream-delta--a'
    previousKey = key
    previousContent = content
    props.context?.textStreamState?.set(key, content)
    return { stable: result.settledContent, delta: result.streamedDelta, deltaClass }
  })
  return (
    <span data-typewriter={props.context?.typewriter ? '1' : undefined} class={`markstream-solid-text-node text-node${(props.node as any)?.center ? ' markstream-solid-text--centered' : ''}`}>
      {streamInfo().stable}
      {streamInfo().delta && <span class={`markstream-solid-text__stream-delta text-node-stream-delta ${streamInfo().deltaClass}`}>{streamInfo().delta}</span>}
    </span>
  )
}
