// packages/markstream-vue2/src/components/FootnoteAnchorNode/FootnoteAnchorNode.vue
<script setup lang="ts">
import { findFootnoteElement } from '../../utils/footnoteTarget'

const props = defineProps<{ node: { type: 'footnote_anchor', id: string, raw?: string } }>()

function scrollToReference(e: MouseEvent) {
  e.preventDefault()
  if (typeof document === 'undefined')
    return
  // FootnoteReferenceNode renders the `<sup id="fnref-<label>">` we scroll back to.
  const anchors = findFootnoteElement(e.currentTarget, `fnref-${String(props.node.id ?? '')}`)
  if (anchors) {
    anchors.scrollIntoView({ behavior: 'smooth' })
  }
}
</script>

<template>
  <a
    class="footnote-anchor text-sm hover:underline cursor-pointer"
    :href="`#fnref-${node.id}`"
    :title="`返回引用 ${node.id}`"
    @click="scrollToReference"
  >
    ↩︎
  </a>
</template>

<style scoped>
.footnote-anchor {
  margin-left: 0.5rem;
  color: var(--link-color, #0366d6);
}
</style>

// packages/markstream-react/src/components/FootnoteAnchorNode/FootnoteAnchorNode.tsx
import type { NodeComponentProps } from '../../types/node-component'
import React, { useCallback } from 'react'
import { findFootnoteElement } from '../../utils/footnoteTarget'

export function FootnoteAnchorNode(props: NodeComponentProps<{ type: 'footnote_anchor', id: string }>) {
  const { node } = props
  const handleScroll = useCallback((event: React.MouseEvent) => {
    event.preventDefault()
    if (typeof document === 'undefined')
      return
    const target = findFootnoteElement(event.currentTarget, `fnref-${String(node.id ?? '')}`)
    if (target)
      target.scrollIntoView({ behavior: 'smooth' })
  }, [node.id])

  return (
    <a
      className="footnote-anchor text-sm hover:underline cursor-pointer"
      href={`#fnref-${node.id}`}
      title={`返回引用 ${node.id}`}
      onClick={handleScroll}
    >
      ↩︎
    </a>
  )
}

export default FootnoteAnchorNode
